version: '3.3'

services:
  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=small
      - POSTGRES_DB=foo_database

# docker exec -it postgres-db psql -U small -d foo_database